### ISSUE TITLE
Assets, Levels, Blueprint structuring

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#1]
The initial commit is using the preset folder struture as provided in a new UE4 project.

However, is this good enough? Some possibilities to consider:
1. Top-most level to contain folders that represent each unique level
2. One level down, will contain the `Assets/`, `Blueprints/`, `Props/` etc. folder
3. Possibly a seperate folder for general junk @ top most level (for files that are currently not in use, that might potentially be used). So the stuff that gets used should not be moved out (to prevent linker problems) but instead be copied over to its relevant location.

**Comment by Schroth94** [comment]
Sounds good!
