### ISSUE TITLE
Make Skeletal Mesh: The player + wheelchair

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#13]
A Human model that can sit, stand(maybe?), push fingers to move the wheel chair joystick

**Comment by Schroth94** [comment]
The mesh exists in a player blueprint now:
Content\VengeanceRising\DiningHallLevel\BP_DiningHallPlayer
(If we have to reproduce it: In the Player Blueprint, for the Inherited Mesh choose "Protagonist" as a skeleton. Under Animation Mode (in the details on the right side) equip it with an Animation Asset, choose "Sitting8" or "Wheelchair_Sit" (both should be working). Then add a Static Mesh, choose "Wheelchair" and attach it to the Inherited Mesh. Then adjust the position and scale of camera, skeleton and wheelchair until it looks good.)

**Comment by Schroth94** [comment]
Standing is ommited. Opened a new issue for combining the mesh with the leap motion
