### ISSUE TITLE
Player Feature: Turning Knobs

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#14]
Player can turn knobs with the mouse or leap motion controller (door knobs, safes, etc.) to trigger something

**Comment by Schroth94** [comment]
Looks like leap motion will not be usable for this. Alternative solution: Gaze on the knob to trigger the door, i.e. change the level

**Comment by Schroth94** [comment]
Closed, because this is becoming the same issue as in #17
