### ISSUE TITLE
Common Object: Hinged Door

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#17]
A door can be triggered to open or close by triggering its knob, to allow/block a player from passing through

**Comment by rodsonchue** [comment]
Since #14 mentions difficulty for the leap motion impl, I suggest that just implement hover over anywhere on the door and not specifically the knob only. Else it would prove to be too cumbersome for a player - unless of course, the door is specifically designed to be locked with a keylock mesh or something along those lines

**Comment by Schroth94** [comment]
no need for that anymore
