### ISSUE TITLE
Level Design: Dining Room

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#2]
Actual details of dining room stuff can also be discussed here

**Comment by Schroth94** [comment]
Actors missing so far:
Windows with rain
Red Curtains
Red Rectangular Carpet
Dishes (Spoon, Knife, Fork, Plate, Wine Glasses, Tablet, Fruits)

**Comment by Schroth94** [comment]
To Do:
Set Right offset for the Fireplace if you are coming from the library
Place sheet of paper with text that leads to the pepper caster
Add sounds: Rain background and chairs crashing sound
