### ISSUE TITLE
Interactable Object: Murder Weapon (Don't know what exactly)

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#32]
Since the game revolves around murder cases, we should eventually need to have a murder weapon of some sort. Possible development from here can be the generation of clues upon interaction with the object.

Since the library level doesn't have much to do atm, I was thinking we could include this in that level as a forewarning of sorts. OR to mark the end of the demo (?)

**Comment by Schroth94** [comment]
In the beginning I intended to have lots of possible murder weapons distributed along the levels. For time reasons, we could maybe stick to one weapon, e.g. a fishing line (we could hide it in the library - it would not be too easy to find) or just a knife (this would be simple to model)

**Comment by Schroth94** [comment]
have now spanner or knife. choose appropriate materials thou
