### ISSUE TITLE
Common Objects: Meshes and Materials

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#36]
James will be searching for static meshes.
Everybody can list stuff he needs for his level:
[x] 1. Potted plant (Entrance Hall)
[ ] 2. Victorian stairs (Entrance Hall)
[ ] 3. Red Curtains (Dining Hall)
[x] 4. Red Rectangular Carpet (Dining Hall)
[ ] 5. Dishes (Spoon, Knife, Fork, Plate, Wine Glasses, Tablet, Fruits) (Dining Hall)
[x] 6. A bag (for the player, to open the inventory)

**Comment by windozZze** [comment]
Added a bunch of fbx files in a zipped folder named "Materials" in Drive -> Asset Market -> All Levels.

Check it out and give me any more suggestions

**Comment by Schroth94** [comment]
The important stuff is existant.
