### ISSUE TITLE
Aesthetics: NPC dialogues

### ISSUE THREAD

**Issue by scottyzm** [VengeanceRising/VengeanceRising#37]
Audio enhancement -> only if we have time left

**Comment by rodsonchue** [comment]
will we be doing caption-like text if we do not have the vocal audio?

**Comment by Schroth94** [comment]
I would like to keep the conversations very basic. Then we could create subtitles. These we will definitely be able to use, even if we decide to do vocal audio in the end

**Comment by rodsonchue** [comment]
We included the speech bubbles. But there are no other characters. So this will happen if details of #33  will be implemented.
