### ISSUE TITLE
Level designer: Main Menu

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#4]
Optional at this point

**Comment by Schroth94** [comment]
Please make a running version until next week. It's okay if it's not beautiful yet, this can be changed until week 13

**Comment by windozZze** [comment]
Yet to implement:
1. Lightning flashes
2. Interactability - With house
3. Flow with levels
4. Music
5. Candles lighting path

Plus I went pretty ham on the fog XP

**Comment by rodsonchue** [comment]
Implemented in schroths last commit
