### ISSUE TITLE
Linking Levels

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#42]
Please make sure your levels are linked correctly. Please add a comment how you imagine your level transitions

**Comment by Schroth94** [comment]
Dining Room:
1 door to main hall
1 door to kitchen (closed)
1 door to library (hidden)
For the hidden door we have to ensure that the player can manually trigger the hiding mechanism to hide and reveal the door

**Comment by rodsonchue** [comment]
Library:
Door to main hall - always accessible
Hidden door to dining hall, (one way access from dining hall only)

**Comment by Schroth94** [comment]
Storage room:
Door to main hall - closed in the beginning. Key is findable in the library
Interactable actor that leads to the hourglass riddle
Return from hourglass riddle to storage room
