### ISSUE TITLE
Create poster for STEPS presentation

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#57]

**Comment by windozZze** [comment]
Inspiration:
1. [Olly Moss Star Wars](http://ollymoss.com/star-wars-trilogy/)
2. [NASA Visions of the future](http://www.jpl.nasa.gov/visions-of-the-future/)

**Comment by Schroth94** [comment]
It's done. See
https://vengeancerising.github.io/Poster/VengeanceRising_Poster.jpg
