### ISSUE TITLE
Playtesting: Bad performance in MainHall in VR

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#66]
Maybe a light rebuild or something can solve the issue.

**Comment by Schroth94** [comment]
It runs only on 47 fps on the lab pcs

**Comment by rodsonchue** [comment]
Use the profiler to find out whats causing it. I suspect the rain particles...

**Comment by Schroth94** [comment]
Al ighting rebuild solved the problem. Maybe the plants had overlapping uv problems
