### ISSUE TITLE
Playtesting: Reticle vanishes behind bottles in library

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#70]
Maybe change the collision settings. Or put a collisionbox around the bottle.

**Comment by rodsonchue** [comment]
The glass IS colliding with the spring arm, but it's reflecting the reticle away. If it becomes too much of a problem, perhaps not using the glass bottles might be a better option.

**Comment by Schroth94** [comment]
I implemented the shift button to toggle the reticle. The problem is not solved perfectly, but we can close this issue.
